feat: ParserIfExpression
Programming-Languages-I/yamil-language pull request #10
Opened 2024-06-20 18:08 UTC by JhaelArce

## Description

Provide a small description of Pull Request.
The implementation of the parser for the if expression was carried out
## Type of Change

Put an `x` in all the boxes that apply:

- [X ] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist

Put an `x` in all the boxes that apply:

- [X ] My commit messages are detailed.
- [ ] My code follows the code style of this project.
- [ ] No existing features have been broken without good reason.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

2024-06-20 22:47 UTC, fabianromeroclaros approved these changes

2024-06-21 01:53 UTC, SebasthianSalpozz approved these changes
I would have liked more tests on the if expression but Good job!! :D

2024-06-21 01:53 UTC, teran-joseluis approved these changes
Good job!

2024-06-21 01:59 UTC, teran-joseluis commented
@JhaelArce Please update your branch to develop. You had files which are not required and we will overwrite them if I merge it.

2024-06-21 02:01 UTC, teran-joseluis requested changes

2024-06-21 02:01 UTC, teran-joseluis commented on package.yaml
> +- HUnit
@JhaelArce Please update your branch to develop. You had files which are not required and we will overwrite them if I merge it.

2024-06-21 02:36 UTC, teran-joseluis requested changes

2024-06-21 02:36 UTC, teran-joseluis commented on .vscode/tasks.json
> +
Please don't commit this directory please.

2024-06-21 02:44 UTC, teran-joseluis approved these changes
Well done!

2024-06-21 02:50 UTC, merged