feat: implement lambda parser
Programming-Languages-I/yamil-language pull request #9
Opened 2024-06-20 03:45 UTC by JosuePrado

## Description

Provide a small description of Pull Request.

## Type of Change

Put an `x` in all the boxes that apply:

- [ ] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist

Put an `x` in all the boxes that apply:

- [ ] My commit messages are detailed.
- [ ] My code follows the code style of this project.
- [ ] No existing features have been broken without good reason.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

2024-06-20 03:48 UTC, fabianromeroclaros reviewed
Add unit test to see the implementation in a better way please.

2024-06-20 03:55 UTC, SebasthianSalpozz requested changes
Lamba is already reserved in reserved names, you should use that one and not create a new one to do it
Just use one of the two

2024-06-20 03:56 UTC, teran-joseluis requested changes

2024-06-20 03:56 UTC, teran-joseluis commented on src/Parser/ParserExpresions.hs
> +              <*> parseLetStatement
Why are you using `parseLetStatement` at the end?

2024-06-20 03:57 UTC, teran-joseluis requested changes

2024-06-20 03:57 UTC, teran-joseluis commented on src/Parser/LexerParser.hs
> +parseLambdaSymbol = string "lambda"
We have lambda in the `languageDef`, you should review that.

2024-06-21 01:34 UTC, SebasthianSalpozz approved these changes
Good Job!! :D

2024-06-21 01:36 UTC, fabianromeroclaros approved these changes

2024-06-21 01:45 UTC, teran-joseluis approved these changes
Good job!

2024-06-21 01:45 UTC, merged